# Kevin Newell
# 10/28/19
#
# This script will generate a report detailing
# which commands are supported by the car the
# adapter is connected to.

import obd

# Initiate OBD connection
conn = obd.OBD()

# Check support for available OBD queries
print('Supported OBD Commands List:')
print('PIDS_A: ' + str(conn.supports(obd.commands.PIDS_A)))
print('STATUS: ' + str(conn.supports(obd.commands.STATUS)))
print('FREEZE_DTC: ' + str(conn.supports(obd.commands.FREEZE_DTC)))
print('FUEL_STATUS: ' + str(conn.supports(obd.commands.FUEL_STATUS)))
print('ENGINE_LOAD: ' + str(conn.supports(obd.commands.ENGINE_LOAD)))
print('COOLANT_TEMP: ' + str(conn.supports(obd.commands.COOLANT_TEMP)))
print('SHORT_FUEL_TRIM_1: ' + str(conn.supports(obd.commands.SHORT_FUEL_TRIM_1)))
print('LONG_FUEL_TRIM_1: ' + str(conn.supports(obd.commands.LONG_FUEL_TRIM_1)))
print('SHORT_FUEL_TRIM_2: ' + str(conn.supports(obd.commands.SHORT_FUEL_TRIM_2)))
print('LONG_FUEL_TRIM_2: ' + str(conn.supports(obd.commands.LONG_FUEL_TRIM_2)))
print('FUEL_PRESSURE: ' + str(conn.supports(obd.commands.FUEL_PRESSURE)))
print('INTAKE_PRESSURE: ' + str(conn.supports(obd.commands.INTAKE_PRESSURE)))
print('RPM: ' + str(conn.supports(obd.commands.RPM)))
print('SPEED: ' + str(conn.supports(obd.commands.SPEED)))
print('TIMING_ADVANCE: ' + str(conn.supports(obd.commands.TIMING_ADVANCE)))
print('INTAKE_TEMP: ' + str(conn.supports(obd.commands.INTAKE_TEMP)))
print('MAF: ' + str(conn.supports(obd.commands.MAF)))
print('THROTTLE_POS: ' + str(conn.supports(obd.commands.THROTTLE_POS)))
print('AIR_STATUS: ' + str(conn.supports(obd.commands.AIR_STATUS)))
print('O2_SENSORS: ' + str(conn.supports(obd.commands.O2_SENSORS)))
print('O2_B1S1: ' + str(conn.supports(obd.commands.O2_B1S1)))
print('O2_B1S2: ' + str(conn.supports(obd.commands.O2_B1S2)))
print('O2_B1S3: ' + str(conn.supports(obd.commands.O2_B1S3)))
print('O2_B1S4: ' + str(conn.supports(obd.commands.O2_B1S4)))
print('O2_B2S1: ' + str(conn.supports(obd.commands.O2_B2S1)))
print('O2_B2S2: ' + str(conn.supports(obd.commands.O2_B2S2)))
print('O2_B2S3: ' + str(conn.supports(obd.commands.O2_B2S3)))
print('O2_B2S4: ' + str(conn.supports(obd.commands.O2_B2S4)))
print('OBD_COMPLIANCE: ' + str(conn.supports(obd.commands.OBD_COMPLIANCE)))
print('O2_SENSORS_ALT: ' + str(conn.supports(obd.commands.O2_SENSORS_ALT)))
print('AUX_INPUT_STATUS: ' + str(conn.supports(obd.commands.AUX_INPUT_STATUS)))
print('RUN_TIME: ' + str(conn.supports(obd.commands.RUN_TIME)))
print('DISTANCE_W_MIL: ' + str(conn.supports(obd.commands.DISTANCE_W_MIL)))
print('FUEL_RAIL_PRESSURE_VAC: ' + str(conn.supports(obd.commands.FUEL_RAIL_PRESSURE_VAC)))
print('FUEL_RAIL_PRESSURE_DIRECT: ' + str(conn.supports(obd.commands.FUEL_RAIL_PRESSURE_DIRECT)))
print('O2_S1_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S1_WR_VOLTAGE)))
print('O2_S2_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S2_WR_VOLTAGE)))
print('O2_S3_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S3_WR_VOLTAGE)))
print('O2_S4_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S4_WR_VOLTAGE)))
print('O2_S5_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S5_WR_VOLTAGE)))
print('O2_S6_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S6_WR_VOLTAGE)))
print('O2_S7_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S7_WR_VOLTAGE)))
print('O2_S8_WR_VOLTAGE: ' + str(conn.supports(obd.commands.O2_S8_WR_VOLTAGE)))
print('COMMANDED_EGR: ' + str(conn.supports(obd.commands.COMMANDED_EGR)))
print('EGR_ERROR: ' + str(conn.supports(obd.commands.EGR_ERROR)))
print('EVAPORATIVE_PURGE: ' + str(conn.supports(obd.commands.EVAPORATIVE_PURGE)))
print('FUEL_LEVEL: ' + str(conn.supports(obd.commands.FUEL_LEVEL)))
print('WARMUPS_SINCE_DTC_CLEAR: ' + str(conn.supports(obd.commands.WARMUPS_SINCE_DTC_CLEAR)))
print('DISTANCE_SINCE_DTC_CLEAR: ' + str(conn.supports(obd.commands.DISTANCE_SINCE_DTC_CLEAR)))
print('EVAP_VAPOR_PRESSURE: ' + str(conn.supports(obd.commands.EVAP_VAPOR_PRESSURE)))
print('BAROMETRIC_PRESSURE: ' + str(conn.supports(obd.commands.BAROMETRIC_PRESSURE)))
print('O2_S1_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S1_WR_CURRENT)))
print('O2_S2_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S2_WR_CURRENT)))
print('O2_S3_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S3_WR_CURRENT)))
print('O2_S4_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S4_WR_CURRENT)))
print('O2_S5_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S5_WR_CURRENT)))
print('O2_S6_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S6_WR_CURRENT)))
print('O2_S7_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S7_WR_CURRENT)))
print('O2_S8_WR_CURRENT: ' + str(conn.supports(obd.commands.O2_S8_WR_CURRENT)))
print('CATALYST_TEMP_B1S1: ' + str(conn.supports(obd.commands.CATALYST_TEMP_B1S1)))
print('CATALYST_TEMP_B2S1: ' + str(conn.supports(obd.commands.CATALYST_TEMP_B2S1)))
print('CATALYST_TEMP_B1S2: ' + str(conn.supports(obd.commands.CATALYST_TEMP_B1S2)))
print('CATALYST_TEMP_B2S2: ' + str(conn.supports(obd.commands.CATALYST_TEMP_B2S2)))
print('STATUS_DRIVE_CYCLE: ' + str(conn.supports(obd.commands.STATUS_DRIVE_CYCLE)))
print('CONTROL_MODULE_VOLTAGE: ' + str(conn.supports(obd.commands.CONTROL_MODULE_VOLTAGE)))
print('ABSOLUTE_LOAD: ' + str(conn.supports(obd.commands.ABSOLUTE_LOAD)))
print('COMMANDED_EQUIV_RATIO: ' + str(conn.supports(obd.commands.COMMANDED_EQUIV_RATIO)))
print('RELATIVE_THROTTLE_POS: ' + str(conn.supports(obd.commands.RELATIVE_THROTTLE_POS)))
print('AMBIANT_AIR_TEMP: ' + str(conn.supports(obd.commands.AMBIANT_AIR_TEMP)))
print('THROTTLE_POS_B: ' + str(conn.supports(obd.commands.THROTTLE_POS_B)))
print('THROTTLE_POS_C: ' + str(conn.supports(obd.commands.THROTTLE_POS_C)))
print('ACCELERATOR_POS_D: ' + str(conn.supports(obd.commands.ACCELERATOR_POS_D)))
print('ACCELERATOR_POS_E: ' + str(conn.supports(obd.commands.ACCELERATOR_POS_E)))
print('ACCELERATOR_POS_F: ' + str(conn.supports(obd.commands.ACCELERATOR_POS_F)))
print('THROTTLE_ACTUATOR: ' + str(conn.supports(obd.commands.THROTTLE_ACTUATOR)))
print('RUN_TIME_MIL: ' + str(conn.supports(obd.commands.RUN_TIME_MIL)))
print('TIME_SINCE_DTC_CLEARED: ' + str(conn.supports(obd.commands.TIME_SINCE_DTC_CLEARED)))
print('MAX_MAF: ' + str(conn.supports(obd.commands.MAX_MAF)))
print('FUEL_TYPE: ' + str(conn.supports(obd.commands.FUEL_TYPE)))
print('ETHANOL_PERCENT: ' + str(conn.supports(obd.commands.ETHANOL_PERCENT)))
print('EVAP_VAPOR_PRESSURE_ABS: ' + str(conn.supports(obd.commands.EVAP_VAPOR_PRESSURE_ABS)))
print('EVAP_VAPOR_PRESSURE_ALT: ' + str(conn.supports(obd.commands.EVAP_VAPOR_PRESSURE_ALT)))
print('SHORT_O2_TRIM_B1: ' + str(conn.supports(obd.commands.SHORT_O2_TRIM_B1)))
print('LONG_O2_TRIM_B1: ' + str(conn.supports(obd.commands.LONG_O2_TRIM_B1)))
print('SHORT_O2_TRIM_B2: ' + str(conn.supports(obd.commands.SHORT_O2_TRIM_B2)))
print('LONG_O2_TRIM_B2: ' + str(conn.supports(obd.commands.LONG_O2_TRIM_B2)))
print('FUEL_RAIL_PRESSURE_ABS: ' + str(conn.supports(obd.commands.FUEL_RAIL_PRESSURE_ABS)))
print('RELATIVE_ACCEL_POS: ' + str(conn.supports(obd.commands.RELATIVE_ACCEL_POS)))
print('HYBRID_BATTERY_REMAINING: ' + str(conn.supports(obd.commands.HYBRID_BATTERY_REMAINING)))
print('OIL_TEMP: ' + str(conn.supports(obd.commands.OIL_TEMP)))
print('FUEL_INJECT_TIMING: ' + str(conn.supports(obd.commands.FUEL_INJECT_TIMING)))
print('FUEL_RATE: ' + str(conn.supports(obd.commands.FUEL_RATE)))

conn.close()